name: Run Qodo Cover
on:
  workflow_dispatch:
    inputs:
      desired_coverage:
        description: "Desired coverage percentage"
        required: false
        default: "80"

permissions:
  pull-requests: write
  contents: write

jobs:
  run-qodo-cover:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run Qodo Cover
        uses: qodo-ai/qodo-ci/.github/actions/qodo-cover@v0.1.12
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          project_language: python
          project_root: .
          code_coverage_report_path: ./coverage.xml
          coverage_type: cobertura
          test_command: "pytest --cov=. --cov-report=xml --cov-report=term"
          model: gpt-4o
          max_iterations: 3
          desired_coverage: 90
          run_each_test_separately: true
          source_folder: .
          test_folder: .
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
